package connect6;


/**
* connect6/ClientLogicPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from connect6.idl
* среда, 25 апрел€ 2018 г., 2:17:34 ћосква, стандартное врем€
*/

public abstract class ClientLogicPOA extends org.omg.PortableServer.Servant
 implements connect6.ClientLogicOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendMove", new java.lang.Integer (0));
    _methods.put ("receiveMove", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // connect6/ClientLogic/sendMove
       {
         String move = in.read_string ();
         this.sendMove (move);
         out = $rh.createReply();
         break;
       }

       case 1:  // connect6/ClientLogic/receiveMove
       {
         String move = in.read_string ();
         this.receiveMove (move);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:connect6/ClientLogic:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientLogic _this() 
  {
    return ClientLogicHelper.narrow(
    super._this_object());
  }

  public ClientLogic _this(org.omg.CORBA.ORB orb) 
  {
    return ClientLogicHelper.narrow(
    super._this_object(orb));
  }


} // class ClientLogicPOA
