package connect6;

/**
* connect6/ClientLogicHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from connect6.idl
* среда, 25 апрел€ 2018 г., 2:17:34 ћосква, стандартное врем€
*/

public final class ClientLogicHolder implements org.omg.CORBA.portable.Streamable
{
  public connect6.ClientLogic value = null;

  public ClientLogicHolder ()
  {
  }

  public ClientLogicHolder (connect6.ClientLogic initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = connect6.ClientLogicHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    connect6.ClientLogicHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return connect6.ClientLogicHelper.type ();
  }

}
