package connect6;


/**
* connect6/ClientLogic.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from connect6.idl
* среда, 25 апрел€ 2018 г., 2:17:34 ћосква, стандартное врем€
*/

public interface ClientLogic extends ClientLogicOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientLogic
