package connect6;

/**
* connect6/ServerLogicHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from connect6.idl
* среда, 25 апрел€ 2018 г., 2:17:34 ћосква, стандартное врем€
*/

public final class ServerLogicHolder implements org.omg.CORBA.portable.Streamable
{
  public connect6.ServerLogic value = null;

  public ServerLogicHolder ()
  {
  }

  public ServerLogicHolder (connect6.ServerLogic initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = connect6.ServerLogicHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    connect6.ServerLogicHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return connect6.ServerLogicHelper.type ();
  }

}
