package connect6;


/**
* connect6/ServerLogicOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from connect6.idl
* среда, 25 апрел€ 2018 г., 2:17:34 ћосква, стандартное врем€
*/

public interface ServerLogicOperations 
{
  void registerClient (connect6.ClientLogic client);
  void sendMove (connect6.ClientLogic client, String move);
  void receiveMove (String move);
} // interface ServerLogicOperations
