package connect6;


/**
* connect6/ServerLogicHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from connect6.idl
* среда, 25 апрел€ 2018 г., 2:17:34 ћосква, стандартное врем€
*/

abstract public class ServerLogicHelper
{
  private static String  _id = "IDL:connect6/ServerLogic:1.0";

  public static void insert (org.omg.CORBA.Any a, connect6.ServerLogic that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static connect6.ServerLogic extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (connect6.ServerLogicHelper.id (), "ServerLogic");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static connect6.ServerLogic read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerLogicStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, connect6.ServerLogic value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static connect6.ServerLogic narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof connect6.ServerLogic)
      return (connect6.ServerLogic)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      connect6._ServerLogicStub stub = new connect6._ServerLogicStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static connect6.ServerLogic unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof connect6.ServerLogic)
      return (connect6.ServerLogic)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      connect6._ServerLogicStub stub = new connect6._ServerLogicStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
